In [1]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

In [2]:
tensor = torch.arange(1, 10, 2, dtype=torch.float32, device=device, requires_grad=True)

print(tensor)
print(tensor.dtype)
print(tensor.device)
print(tensor.shape)
print(tensor.requires_grad)

tensor([1., 3., 5., 7., 9.], requires_grad=True)
torch.float32
cpu
torch.Size([5])
True


In [ ]:
def out(name, tensor):
    print(f'{name}:', tensor, sep='\n', end='\n\n')

# other
out("empty", torch.empty(2, 3))  # uninitialized data
out("zeros", torch.zeros(2, 3))
out("ones", torch.ones(2, 3))
out("full", torch.full((2, 3), 10))
out("rand", torch.rand(3, 5))
out("randn", torch.randn(3, 5))
out("randint", torch.randint(-4, 4, (3, 5)))
out("eye", torch.eye(4, 2))
out("linspace", torch.linspace(1, 10, 20).reshape(4, 5))
out("empty", torch.empty(1, 5).normal_(mean=3, std=10))

x = torch.arange(6).reshape(2, 3)
print(x)
out("fill", torch.fill(x, 3))
out("diag", torch.diag(x))
out("transpose", x.T)  # special case of permute
out("transpose", x.t())
out("permutation", x.permute(1, 0))

empty:
tensor([[3.9872e-13, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])

zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

full:
tensor([[10, 10, 10],
        [10, 10, 10]])

rand:
tensor([[0.7366, 0.2152, 0.2668, 0.7426, 0.7543],
        [0.9588, 0.8689, 0.5684, 0.5189, 0.6131],
        [0.4844, 0.8749, 0.0458, 0.2407, 0.3235]])

randn:
tensor([[ 0.6320,  0.4125,  0.9879, -1.6783,  0.2526],
        [ 0.9923, -0.2880, -0.1074, -0.6524,  0.4419],
        [ 0.6643, -1.9167,  0.1597,  0.1707,  0.1039]])

randint:
tensor([[-1, -3,  3, -2, -1],
        [-2,  3,  1, -4, -4],
        [ 2,  3, -1, -2,  0]])

eye:
tensor([[1., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.]])

linspace:
tensor([[ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947],
        [ 3.3684,  3.8421,  4.3158,  4.7895,  5.2632],
        [ 5.7368,  6.2105,  6.6842,  7.1579,  7.6316],
        [ 8.1053,  8.5789,  9.0526,  9.5263, 10.0000]])

In [17]:
x = torch.arange(3)
print(x.bool())
print(x.short())  # int16
print(x.int())  # int32
print(x.long())  # int64
print(x.half())  # float16
print(x.float())  # float32
print(x.double())  # float64

tensor([False,  True,  True])
tensor([0, 1, 2], dtype=torch.int16)
tensor([0, 1, 2], dtype=torch.int32)
tensor([0, 1, 2])
tensor([0., 1., 2.], dtype=torch.float16)
tensor([0., 1., 2.])
tensor([0., 1., 2.], dtype=torch.float64)


In [ ]:
# method -> normal method
# method_ -> in-place method
x = torch.tensor([1,2,3])
y = torch.tensor([5,4,3])

z = torch.add(x, y)
z = x.add(y)
z = x.add_(y)
print(z)
print(x)
print(y)

# element wise mul
z = x * y

# dot product
z = torch.dot(x, y)

# matrix multiplication
x1 = torch.rand(2, 3)
x2 = torch.rand(3, 5)
z = torch.mm(x1, x2)  # 2x5

# batch matrix mul
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand(batch, n, m)
tensor2 = torch.rand(batch, m, p)
out = torch.bmm(tensor1, tensor2)  # (batch, n, p)

# broadcasting -> automatic expansion of tensor dimensions so that they can be compatible for element-wise operations
x1 = torch.rand(4,5)
x2 = torch.rand(1,5)
z = x1 - x2

tensor([6, 6, 6])
tensor([6, 6, 6])
tensor([5, 4, 3])


In [26]:
x = torch.randint(10, (6,))
values, ids = torch.max(x, dim=0)

print(x)
print(values, ids)

tensor([5, 2, 6, 3, 7, 9])
tensor(9) tensor(5)
